### ISSUE TITLE
"officially" support iOS 8 extensions

### ISSUE THREAD

**Issue by piemonte** [segmentio/analytics-ios#213] opened 2014-10-15 23:54 UTC
hey there,

iOS 8 enables the ability to develop out of app extensions. the architecture of these extensions make some api unavailable, such as UIApplication.

it would be nice to define a means for avoiding it's use in the future or just updating the tutorial to explicitly state the install is different.

here was the issue tracking AFNetworking changes:

AFNetworking/AFNetworking#2119

**Comment by robmaceachern** [comment] 2015-06-04 04:53
+1

Is there a workaround available right now?

**Comment by pomarec** [comment] 2015-11-16 15:30
+1

**Comment by hunghoangterralogic** [comment] 2016-07-20 03:16
Hey, is there any update on this ?

**Comment by f2prateek** [comment] 2016-07-20 06:55
For now, the workaround is to use our HTTP API directly https://segment.com/docs/sources/server/http/

**Comment by tvarady** [comment] 2016-11-24 16:36
Is this on your roadmap? Or should we start to think about workarounds?

**Comment by f2prateek** [comment] 2016-11-24 18:07
It's still on the roadmap (the issue will be closed if it is not). No timeline yet, as mentioned you can use the HTTP API directly for now.

**Comment by danieljimenez** [comment] 2016-11-24 18:34
That's not really a work around for apps that expect to be able to handle events while not connected to the internet.

**Comment by f2prateek** [comment] 2016-11-24 19:58
@danieljimenez yes you will have to write your own queueing mechanisms. If you need a starting point, you can fork the SDK and remove the bits you don't need.

**Comment by tvarady** [comment] 2016-12-13 15:04
Now I checked Segment's HTTP API, and it looks like I have to re-implement parts of Segment iOS SDK to make it work... I have to collect Context data, identify user, implement NSURLSession to access the API, just like the SDK itself does. So it's not so trivial, and it's just because some lines are not compiling in extension context.

**Comment by f2prateek** [comment] 2016-12-13 17:20
@tvarady you could fork the sdk in the meantime and remove/change the bits you don't need, likely you don't need to write one from scratch. If you do, let us know and that will help us bring that functionality into the core library!

**Comment by LeoNatan** [comment] 2016-12-30 00:38
It's embarrassing that an issue like this remains open since 2014. Shows how serious the developers are about iOS development. This should turn a warning sign for any iOS developer looking to use this framework or service. Simply do not.

**Comment by f2prateek** [comment] 2016-12-30 01:09
@LeoNatan I apologize for the delay. We definitely want to support extensions (which is why the issue is still open). It hasn't received as much attention because it is one of our least requested features — there are <15 people combined who have expressed interest on this issue and via our internal Zendesk so far 

In addition, the change is also not simple to implement which has made it hard to justify the investment into it so far. We've been making changes to the library internally to make this easier to support in the future, but I understand why it can seem like progress is slow.

Likely this doesn't help you and is frustrating, but I just wanted to try to explain our side.

FWIW we do accept contributions (e.g. tvOS support was added by a contributor #572). Happy to accept a PR!

**Comment by LeoNatan** [comment] 2016-12-30 02:05
What about users you are not aware of?
http://stackoverflow.com/q/41388834/983912

**Comment by f2prateek** [comment] 2016-12-30 05:34
@LeoNatan there certainly might be users we're not aware of - I've added a note for that particular reference internally. Letting us know helps us prioritize the request - and as we see more demand we'll certainly be raising the urgency of the request.

**Comment by ethanhuang13** [comment] 2017-01-05 10:19
We use Segment with Mixpanel. Mixpanel support extension-only integration. See https://github.com/mixpanel/mixpanel-iphone

**Comment by HongDongZhao** [comment] 2017-01-11 03:17
I need the appExtension support indeed.

I am evaluating Segment SDK for my existing app. I run into the following errors.

It would be highly appreciated if you enable Segment to  support appExtension soon.

Thanks.

Pods/Analytics/Analytics/Classes/Internal/SEGSegmentIntegration.m:264:40: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.
/Pods/Analytics/Analytics/Classes/Internal/UIViewController+SEGScreen.m:41:45: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

**Comment by ozetadev** [comment] 2017-02-15 00:11
Add me to the list of people requesting it. Then again, support didn't even know they published a swift library, so I doubt this gets changed.

**Comment by f2prateek** [comment] 2017-02-15 01:45
@ozetadev that's because I've told our support team to not mention the swift library. This library does indeed support swift (as noted in it's readme https://github.com/segmentio/analytics-swift#analytics-swift-), and in general most developers (wrongly) assume they must `analytics-swift` from swift and not `analytics-ios`, `analytics-swift` is only really useful in a very small % of applications. If you're an advanced user and understand the tradeoffs, by all means use `analytics-swift`!

**Comment by ozetadev** [comment] 2017-02-15 17:59
@f2prateek there was no assumption on which library to use, however, when it was discovered that your objective-c library cannot be referenced by a class used in an iMessage extension, I took a look at your swift library as a possible solution.

**Comment by f2prateek** [comment] 2017-02-15 18:10
That's a perfect example of when you should look into the swift library :)

**Comment by JamesKuang** [comment] 2017-03-22 20:55
Would like extension support on this library as well!

**Comment by ozetadev** [comment] 2017-03-23 21:47
@jameskuang you're better off just using another service, this whole thread is an excellent indicator of the type of support you'll receive from segment.

**Comment by f2prateek** [comment] 2017-03-23 21:59
hey @ozetadev, sorry to hear that :(. Happy to accept a PR from you or anyone else if you feel about this so strongly. As I mentioned before, there just isn't enough demand for this request for us to invest the time into this at this time.

**Comment by tonyxiao** [comment] 2017-06-15 17:00
Support is now in dev. Closing issue.

**Closed by tonyxiao** 2017-06-15 17:00 UTC
Labels: feature
