### ISSUE TITLE
Build error in SEGAnalyticsIntegration.m re: TRVSDictionaryWithCaseInsensitivity.h w/ CocoPods v0.38.x

### ISSUE THREAD

**Issue by julianwa** [segmentio/analytics-ios#388] opened 2015-07-30 13:35 UTC
Repro:

1. Use `pod lib create <name>` to initialize a new Pod that includes a test app.
2. Include `s.dependency 'Analytics/Segmentio'` in the Pod's podspec. (latest version was 1.12.2 as of the creation of this issue.)
3. Run `pod install` for the sample app, which depends on the Pod
4. Attempt to build the sample app.

Observe:  `#import <TRVSDictionaryWithCaseInsensitivity.h>` results in the following error: `Users/julianwa/Projects/SegmentRepro/Example/Pods/Analytics/Analytics/SEGAnalyticsIntegration.m:5:9: error: 'TRVSDictionaryWithCaseInsensitivity.h' file not found with <angled> include; use "quotes" instead`.

Notes:
- This only started happening with CocoaPods v0.38.x
- Should the import be `#import <TRVSDictionaryWithCaseInsensitivity/TRVSDictionaryWithCaseInsensitivity.h>`? This fixes the build break.

Clean repro repo: https://github.com/julianwa/SegmentRepro

**Comment by f2prateek** [comment] 2015-07-30 23:23
Thanks for the sample. Couldn't actually reproduce unfortunately - https://cloudup.com/cw2sW3c5lYB

**Comment by f2prateek** [comment] 2015-07-30 23:23
(tried with both 0.38.2 and 0.37.x)

**Comment by julianwa** [comment] 2015-07-31 01:55
Hmm, did you compile `SegmentRepro-Example`?
```
~/SegmentRepro/Example (master) $ xcodebuild -version
Xcode 6.4
Build version 6E35b

~/SegmentRepro/Example (master) $ xctool --version
0.2.3

~ $ pod --version
0.38.2

~ $ git clone git@github.com:julianwa/SegmentRepro.git
Cloning into 'SegmentRepro'...
remote: Counting objects: 143, done.
remote: Compressing objects: 100% (105/105), done.
remote: Total 143 (delta 22), reused 143 (delta 22), pack-reused 0
Receiving objects: 100% (143/143), 66.82 KiB | 0 bytes/s, done.
Resolving deltas: 100% (22/22), done.
Checking connectivity... done.

~ $ cd SegmentRepro/Example/

~/SegmentRepro/Example (master) $ pod install
Updating local specs repositories
Analyzing dependencies
Fetching podspec for `SegmentRepro` from `../`
Downloading dependencies
Using Analytics (1.12.2)
Using SegmentRepro (0.1.0)
Using TRVSDictionaryWithCaseInsensitivity (0.0.2)
Generating Pods project
Integrating client project
Sending stats

~/SegmentRepro/Example (master) $ xctool -workspace SegmentRepro.xcworkspace -scheme SegmentRepro-Example
```

Result:
```
/Users/julianwa/SegmentRepro/Example/Pods/Analytics/Analytics/SEGAnalyticsIntegration.m:5:9: error: 'TRVSDictionaryWithCaseInsensitivity.h' file not found with <angled> include; use "quotes" instead
#import <TRVSDictionaryWithCaseInsensitivity.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        "TRVSDictionaryWithCaseInsensitivity.h"
1 error generated.
```

**Comment by f2prateek** [comment] 2015-07-31 03:01
@julianwa Ah shoot, I totally forgot that step. I can see it now, will investigate further. Thanks for bringing it up!

**Comment by julianwa** [comment] 2015-07-31 12:31
No prob. I'm glad it's not just on my machine! :)

See my suggested fix:

`#import <TRVSDictionaryWithCaseInsensitivity.h> -> #import <TRVSDictionaryWithCaseInsensitivity/TRVSDictionaryWithCaseInsensitivity.h>`,

which I believe is more standard CocoaPods include use, e.g. `#include <PodName/Header.h>`

**Comment by julianwa** [comment] 2015-07-31 19:17
Thanks!

**Comment by dbachrach** [comment] 2015-08-04 21:47
This looks like it got checked into the `updates` branch and has not hit master yet. This breaks our builds when using the analytics library. Any chance we can get this merged into master?

**Comment by jonah-williams** [comment] 2015-08-06 23:42
As @dbachrach noted this is still an issue in the 2.0.1 release due to the `updates` branch not being merged. @f2prateek I'm not sure how you handle branches and issues in this repo but maybe this issue should still be open until a fix reaches a release?

**Closed** 2015-08-10 17:11 UTC

**Comment by travisjeffery** [comment] 2015-08-10 17:26
@jonah-williams @dbachrach Got it in https://github.com/segmentio/analytics-ios/commit/24653afd21c49ddead1ecbb114c3e81c51613ca9. Thanks!

**Comment by jonah-williams** [comment] 2015-08-11 21:39
Thanks @travisjeffery, happily using 2.0.2 now :+1:
