### ISSUE TITLE
Deadlock issue with forwardSelector:arguments:options: method

### ISSUE THREAD

**Issue by bbernberg** [segmentio/analytics-ios#683] opened 2017-04-18 21:22 UTC
We are seeing a repeatable deadlock issue due to the `@synchronized(self)` lock in `SEGIntegrationsManager.m`'s `forwardSelector:arguments:options:` method.  We are seeing the issue when the app becomes active and the `handleAppStateNotification` path is executed.

**Comment by bbernberg** [comment] 2017-04-18 21:55
FYI, here is an example snapshot of the deadlock.  As can be seen, Thread 26 (which has the lock) is attempting to access the main thread, which is attempting to obtain lock:

![screen shot 2017-04-18 at 5 52 13 pm](https://cloud.githubusercontent.com/assets/1385086/25154746/ded29d80-245f-11e7-841e-f0fe307689a9.png)

**Comment by raylillywhite** [comment] 2017-04-19 20:56
Pretty sure this is the same issue, but the stack trace where we're seeing this is a bit different, so in case it's helpful for debugging:

![](http://d.pr/i/tBz5/kzlUFiG6+)
![](http://d.pr/i/13S3J/5sPKOngV+)

**Comment by f2prateek** [comment] 2017-04-19 22:33
Thanks for the report! @tonyxiao is looking into this.

**Comment by bbernberg** [comment] 2017-04-19 23:58
FYI I tried a different approach using serial dispatch queues & a serial `NSOperationQueue` but both approaches ran into the same problem.  Is there a reason the App State Notifications need to be handled synchronously from the main thread?  I don't have enough background knowledge of the full system to understand if this is truly a requirement.

**Comment by tonyxiao** [comment] 2017-04-21 15:44
@bbernberg I'm trying to investigate this right now. Do you happen to have a minimal example that you can put on github reproducing this issue?

**Comment by raylillywhite** [comment] 2017-04-21 23:21
This regularly reproduces it on my iPhone 7 Plus from backgrounding and foregrounding the app a couple times: https://gist.github.com/raylillywhite/cb74d4d1b9325bfcde94119170be55ec

In the app where I'm experiencing it, we're obviously not sending anywhere near that many events, and it happens every time we turn on airplane mode, launch the app, background it, turn off airplane mode, foreground the app. I wasn't able to successfully reproduce that with a minimal example though.

**Comment by bbernberg** [comment] 2017-04-24 14:05
@raylillywhite 's example looks perfect.  It definitely seems to be the App State Notifications deadlocking with other events fired from the main thread.

**Comment by tonyxiao** [comment] 2017-04-25 21:38
@bbernberg @raylillywhite we've got a fix on `deadlock` branch (https://github.com/segmentio/analytics-ios/pull/684) that works in our test setup, I'd love to get some confirmation that it does indeed resolve the issue you're seeing. Can you try out the branch with `pod 'Analytics', :git => 'https://github.com/segmentio/analytics-ios.git', :branch => 'deadlock'`. We can make a new release with this fix right after.

**Comment by raylillywhite** [comment] 2017-04-25 23:05
That branch does fix the issue in our main app as well :tada: Thanks for making this fix a priority!

**Comment by bbernberg** [comment] 2017-04-26 13:52
@tonyxiao this unfortunately did not fix the issue for us.  Here's a stack trace from that branch:

![screen shot 2017-04-26 at 9 49 57 am](https://cloud.githubusercontent.com/assets/1385086/25437968/ffe9fb06-2a65-11e7-9c14-732143d88b06.png)

**Comment by tonyxiao** [comment] 2017-04-26 14:30
@bbernberg my best guess right now is that Taplytics tries to dispatch to the main thread synchronously within their [`logEvent:value:metadata`](https://github.com/taplytics/taplytics-ios-sdk/blob/master/Taplytics.framework/Headers/Taplytics.h#L126) method. However their SDK is closed source so it's not easy to tell. Will try to contact them to get more info and report back here.

cc @TeresaNesteby @ladanazita

**Comment by bbernberg** [comment] 2017-05-24 17:26
@tonyxiao any update on this?  We are still seeing this issue in production unfortunately.

**Comment by tonyxiao** [comment] 2017-05-24 18:06
@bbernberg We reached out to Taplytics but have not heard back yet. In the meantime I'm going to add a workaround in the core library.

**Comment by f2prateek** [comment] 2017-05-26 17:53
@tonyxiao did we add a workaround here?

**Comment by tonyxiao** [comment] 2017-05-31 16:21
on the roadmap, will circle back to this next week.

**Comment by bbernberg** [comment] 2017-06-21 14:56
Any more updates on this?  We are about to launch a feature that is seeing this issue at a very high rate.  My previous attempts at workarounds are no longer working.

**Comment by ladanazita** [comment] 2017-06-22 17:42
@bbernberg Sorry for the delay here. I'm going to reach out to Taplytics again and see if they can jump in and help out. Will update as soon as I have more.

**Comment by tonyxiao** [comment] 2017-06-24 00:20
@bbernberg we got in touch with the Taplytics team and are sorting out the right solution together.

**Comment by ladanazita** [comment] 2017-06-28 00:46
@bbernberg I apologize for the delay again. 

We decided to change our Taplytics integration to call Taplytics asynchronously rather than have Taplytics/Segment modify the core SDK.

Since this issue is outside the scope of our core SDK, I will close this here and track this issue internally in addition to the Taplytics repo for you to follow: 
https://github.com/segment-integrations/analytics-ios-integration-taplytics/issues/17

**Closed by ladanazita** 2017-06-28 00:46 UTC
