### ISSUE TITLE
Can't update user traits for previously identified user without providing userId

### ISSUE THREAD

**Issue by brianmichel** [segmentio/analytics-ios#635] opened 2016-11-22 21:09 UTC
We have many traits for our user, but they come in asynchronously. This means that we need to ensure that we call the `identify` method with each set of additional traits _and_ the original ID otherwise we'll just get an "Anonymous ID" in our stream of events, and future events for integrations that require `userId` to be set will fail.

We'd like a way to update the traits that the Segment SDK is sending, without also having to pass in the identifier of the user that has already been set.

**Comment by f2prateek** [comment] 2016-11-22 21:22
Could you confirm if this is the scenario you're referring to?

1. call analytics.identify with userId "foo"
2. turn on a client side integration 
3. call analytics.track with event "bar"

In this case the newly turned on client side integration may associate the event with the anonymousId instead of the previously provided userId "foo".

**Comment by brianmichel** [comment] 2016-11-22 21:28
Hey @f2prateek here is the scenario of events: 

1. call `analytics.identify` with userId `foo`
2. track some events through the `analytics.track` call
3. new trait information has been delivered to us, so we call `analytics.identify` with the trait dictionary  and do **not** specify a userId.

We would basically like an `analytics.traits = traitsDictionary` call so we do not have to go through the identify path if possible since it seems weird to send redundant information through the `identify` call if we're really just updating the traits.

**Comment by f2prateek** [comment] 2016-11-22 21:44
@brianmichel Hmmm..... I'm not sure I understand what's not working in the scenario you shared. In your scenario it's perfectly fine to send only the new traits and skip the userId on subsequent calls after the first time.

The identify call is meant for 2 purposes - a) telling us who the user is (i.e. call identify with a userId) and b)  updating traits about a user (i.e. call identify with traits)

If you don't call identify with the new traits and just did `analytics.traits = traitsDictionary` - there is no action triggered indicating to integrations that "hey there's new information about an user, update it"

**Comment by brianmichel** [comment] 2016-11-22 22:55
@f2prateek I think I understand the `identify` call, and it seems that our error is only an error with the Outbound integration turned on. 

I've created a sample project [here](https://github.com/brianmichel/SegmentIdentifyUnset) that can help demonstrate the problem. Please email me to get credentials to log into my Segment test account to view the debugger as the events come through.

To simulate what we're experiencing run the sample app and perform the following actions:

1. Tap the "Identify" button.
2. Tap the "Track Event" button.
3. Tap the "Identify With Traits" button.
4. Tap the "Track Event" button.

Notice in the debugger you should see a stream of events similar to the following:
![screen shot 2016-11-22 at 5 53 28 pm](https://cloud.githubusercontent.com/assets/63919/20545342/aac2e672-b0dc-11e6-9076-43a304755c2a.png)

Please note that our "Identify With Traits" code does _not_ pass an ID into that call, it's really just trying to update traits of the pre-identified user, https://github.com/brianmichel/SegmentIdentifyUnset/blob/master/SegmentAnonymousIdTest/ViewController.swift#L25

**Comment by f2prateek** [comment] 2016-11-22 23:13
@brianmichel can you send me the slug and workspace of your segment project?

**Comment by brianmichel** [comment] 2016-11-22 23:23
@f2prateek https://segment.com/brian-michel/sources/ios/overview

**Comment by f2prateek** [comment] 2016-11-22 23:33
Ok I see what the issue - calling `[analytics identify:nil traits:foo]` will set the userId to nil (https://github.com/segmentio/analytics-ios/blob/master/Analytics/Classes/Internal/SEGSegmentIntegration.m#L329) on disk. This means that even though subsequent actions are checking the disk for the userId and attaching it (https://github.com/segmentio/analytics-ios/blob/master/Analytics/Classes/Internal/SEGSegmentIntegration.m#L437), they attach nil.

In the meantime - the fix would be to not call identify with `nil`.

But we'll fix this, thanks for the report!

**Comment by f2prateek** [comment] 2016-11-23 00:03
For more reference this isn't a recent regression but has been the behaviour since inception https://github.com/segmentio/analytics-ios/commit/af22e8651357f804a280d1538c29759090e9217f.

For now, as I mentioned - the fix would be to not call identify with nil userId.

**Comment by brianmichel** [comment] 2016-11-23 16:19
@f2prateek this is great news, thanks!

**Comment by f2prateek** [comment] 2017-11-23 22:17
Tracking internally on JIRA as well — https://segment.atlassian.net/browse/LIB-133

**Comment by Dfmarulanda** [comment] 2020-01-13 23:05
There is any way to update the trait without calling all the identify with id?

**Comment by robmaceachern** [comment] 2021-02-24 17:26
We'd also like a way to specify additional traits (or update existing traits) without calling `identify`.

**Comment by alanjcharles** [comment] 2021-08-04 21:45
Closing as the internal jira has been marked as "Won't Fix" for some time now and we are currently investing development time for new functionality in the analytics-swift pilot. I would recommend checking it out as it gives you a lot more flexiibility and control over your analytics implementation. 

https://github.com/segmentio/analytics-swift

**Closed by alanjcharles** 2021-08-04 21:45 UTC
Labels: bug, jira
