### ISSUE TITLE
Linker error after "pod install"

### ISSUE THREAD

**Issue by n8stowell82** [segmentio/analytics-ios#522] opened 2016-04-26 03:37 UTC
Hello I am updating an old project that had used this lib and am trying to get everything updated to current versions.  Everything was working fine, but all of a sudden my entire project just quite compiling with this error:

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_TRVSDictionaryWithCaseInsensitivity", referenced from:
      objc-class-ref in libAnalytics.a(SEGAnalyticsIntegration.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It was literally compiling and running fine the night before, and with no code changes between then, I started getting this error.  I have no idea why this is happening, and I have tried everything I know to resolve this issue.  Please any help on this would be greatly appreciated

here are the pods related to this project:
```
    pod 'Analytics', '~> 3.0'
    pod 'Segment-GoogleAnalytics'
    pod 'Segment-Mixpanel'
    pod 'Segment-Amplitude'
```

**Comment by f2prateek** [comment] 2016-04-27 21:55
This is most likely because another dependency has a conflict. Best option is to  remove other dependencies one by one and see which caused the conflict.

**Comment by n8stowell82** [comment] 2016-04-27 22:27
Unfortunately this is not the case. Only by removing this pod and
commenting out all references does the error resolve

-- 
Nathan Stowell
Sent with Airmail

**Comment by f2prateek** [comment] 2016-04-27 23:16
Can you send us your whole Podfile?

**Comment by n8stowell82** [comment] 2016-04-28 14:42
`platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

def shared_pod
    pod 'FMDB/SQLCipher'
    pod 'JSONModel'
    pod 'Appboy-iOS-SDK', '~>2.17'
    pod 'OpenSSL-Universal', '1.0.1.k'
    pod 'CustomBadge'
    pod 'CocoaLumberjack', '~> 1.9'
    pod 'SVGKit'
    pod 'Obfuscator', '~> 2.0'
    pod 'DateTools'
end

target "App" do
    shared_pod
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'Analytics', '~> 3.0'
    pod 'Segment-GoogleAnalytics'
    pod 'Segment-Mixpanel'
    pod 'Segment-Amplitude'
    pod 'Form', git: 'git@github.com:hyperoslo/Form.git', branch: 'remove-hex-dependency'
end

target "AppExtension" do
    shared_pod
end`

**Comment by n8stowell82** [comment] 2016-04-28 14:46
This is a slight side issue but I figured this would be the best place to bring this up.  I am unable to use your analytics tools in my app extension.  when installing for the extension I get this nasty error message: 

> /Pods/Amplitude-iOS/Amplitude/Amplitude.m:462:47: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

on these lines:

`UIApplicationState state = [UIApplication sharedApplication].applicationState;`

**Comment by hankim813** [comment] 2016-05-09 18:44
@f2prateek any update?

**Comment by n8stowell82** [comment] 2016-05-09 18:46
@f2prateek @hankim813 one more piece of information.  I noticed the other day that this was working fine when compiling to the simulator, but as soon as I switched to build to an real device the error popped up again.  Any updates on how to resolve this issue would be great. Thank you for your time

**Comment by jessepollak** [comment] 2016-05-12 00:33
+1 hitting this issue as well

**Comment by f2prateek** [comment] 2016-06-02 16:00
@jessepollak are you using the same integrations?

@n8stowell82 can you share your Podfile.lock? What if you try pinning the versions for the integrations you are using?

**Comment by f2prateek** [comment] 2016-06-06 19:07
I'm closing this issue since I couldn't reproduce this with Cocoapods 1.0.1 

Podfile:
```
  pod 'Analytics', '~> 3.0'
  pod 'Segment-GoogleAnalytics', '~> 1.0'
  pod 'Segment-Mixpanel', '~> 1.0'
  pod 'Segment-Amplitude', '~> 1.0'
```

Podfile.lock
```
PODS:
  - Amplitude-iOS (3.6.0)
  - Analytics (3.0.7)
  - Expecta (1.0.3)
  - GoogleAnalytics (3.14.0)
  - GoogleIDFASupport (3.14.0)
  - Mixpanel (2.9.9):
    - Mixpanel/Mixpanel (= 2.9.9)
  - Mixpanel/Mixpanel (2.9.9)
  - Segment-Amplitude (1.2.0):
    - Amplitude-iOS (~> 3.6.0)
    - Analytics (~> 3.0.7)
  - Segment-GoogleAnalytics (1.0.1):
    - Analytics (~> 3.0.0)
    - GoogleAnalytics (~> 3.14)
    - GoogleIDFASupport (~> 3.14)
  - Segment-Mixpanel (1.0.4):
    - Analytics (~> 3.0.0)
    - Mixpanel (~> 2.9.0)
  - Specta (1.0.4)

DEPENDENCIES:
  - Analytics (~> 3.0)
  - Expecta
  - Segment-Amplitude (~> 1.0)
  - Segment-GoogleAnalytics (~> 1.0)
  - Segment-Mixpanel (~> 1.0)
  - Specta

SPEC CHECKSUMS:
  Amplitude-iOS: bc8163268d4107130364eaa674e111b41b073b78
  Analytics: b342fb4f43fa4f97ca6f4358b44d3295217ba294
  Expecta: 9d1bff6c8b0eeee73a166a2ee898892478927a15
  GoogleAnalytics: 9be1afdb8deeac4bb5f13ca7f7d3b9db2a1f43dc
  GoogleIDFASupport: aaf8c10bd429abb1c15349d5252244f5eda8ead1
  Mixpanel: 818d1940c2d9402453b349545022a86968097f57
  Segment-Amplitude: 26576f37f31c5cd3512de03188fe9ca9e4d7dcba
  Segment-GoogleAnalytics: ffea73c99196720b28b58ea93bcc0e6d11f172e1
  Segment-Mixpanel: dfa4297d1aa6ccea505efcc040d3adb0e19ed081
  Specta: 69bb134672aae190a1379ff91df07dad8dd1f869

PODFILE CHECKSUM: 8cea54b6b3a67a901d82196fd566bae798051561

COCOAPODS: 1.0.1
```

If you can send a more precise Podfile that might help surface the issue.

**Closed by f2prateek** 2016-06-06 19:07 UTC
