### ISSUE TITLE
Core Telephony for tvOS

### ISSUE THREAD

**Issue by krzemienski** [segmentio/analytics-ios#791] opened 2018-10-03 21:34 UTC
if you pull master in a tvos app it is looking for CoreTelelphony,
<img width="1405" alt="screen shot 2018-10-03 at 5 34 03 pm" src="https://user-images.githubusercontent.com/16410101/46440819-95c7ed80-c732-11e8-8f24-e1ee287348c1.png">

**Comment by f2prateek** [comment] 2018-10-03 22:02
Is this with Carthage?

**Comment by f2prateek** [comment] 2018-10-03 22:05
Digging in deeper, I'm pretty sure the issue is likely from https://github.com/segmentio/analytics-ios/pull/773.

As a workaround, you should be able to use anything before that commit.

**Comment by f2prateek** [comment] 2018-10-04 00:06
@fathyb do you have any suggestions on how to fix this?

**Comment by krzemienski** [comment] 2018-10-04 06:00
@f2prateek im pretty sure the way to tackle would be to do something like so in the podspec, I give it a shot sometime this week in that playing with your podspecs file.
```
s.tvos.frameworks = 'foo'
s.ios.frameworks = 'foo2'
```

**Comment by krin-san** [comment] 2019-07-30 07:58
How you `make lint` job even succeeded with such a mistake?

Please, don't make a 3.8.0 release without this fix – it will be such a shame otherwise.

**Comment by bsneed** [comment] 2020-01-30 21:06
This has been fixed in the latest beta.

**Closed by bsneed** 2020-01-30 21:06 UTC
